### ISSUE TITLE
Your project's name conflicts with an existing PEG parser project.

### ISSUE THREAD

**Issue by otac0n** [Qix-/pegasus#2]
Hi, I just discovered this project, and wanted to inform you that my PEG parser project has been using the name Pegasus since July of 2012 with our first release in August of the same year.

Here are some links to my project:
http://otac0n.com/Pegasus/
https://github.com/otac0n/Pegasus

I would kindly request that you consider renaming your project to avoid confusion when people are doing web searches for either of our projects.

I feel it is right for your project to rename for these reasons:
* There is confusion when people search for "pegasus parser" as to whether our projects are associated
* My project has been using the name "Pegasus" for 4 years more than your project.
* Your project is currently released as version `0.1.3 `, which implies that it has not yet had its first official release.  According to SemVer ([officially recommended by PEP 440](https://www.python.org/dev/peps/pep-0440/#semantic-versioning)), it is still entirely appropriate to make changes to the project name:  
> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by Qix-** [comment]
There are many instances of software sharing names. I wrote this package a long time ago and it is still used in development In few places. Seeing as how it took you so long to find it here, I don't think it'll be a problem - especially since I have the Pegasus name on pypi and your project is in C#.

**Comment by otac0n** [comment]
The distinction here is that both of our projects are providing closely related services.  I would also like to reserve the right to expand support of my parser compiler to include Python.

**Comment by Qix-** [comment]
Sorry, I'm not willing to change the name.
